spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/user_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    timeout: 86400
  profiles:
    active: dev
    main:
      allow-circular-references: true
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
  file:
    path:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命令
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  mapper-locations: classpath*:/mapper/*.xml
